name: Update README Table

on:
  push:
    branches:
      - main  # Or your target branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Pull the latest changes from the remote repository
        run: |
          git fetch origin
          git checkout main
          git pull origin main

      - name: Read existing "available templates" section (optional)
        run: |
          set +e
          # Check for the "available templates" section in the README
          available_templates_line=$(grep -ni "available templates" README.md | cut -d: -f1)
          if [[ ! -z "$available_templates_line" ]]; then
            echo "Found 'available templates' section. Updating..."
          else
            echo "No 'available templates' section found. Adding new section..."
          fi

      - name: Generate new table content in Markdown
        run: |
          files=$(find ./templates -type f)
          content=""
          for file in $files; do
            file_name=$(basename "$file" .yaml)
            link="https://snbig.github.io/Vulnerable-Pages/templates/$file_name"
            content+="- [$file_name]($link)\n"
          done
          echo "$content" > table_content.txt

      - name: Update README
        run: |
          if [[ ! -z "$available_templates_line" ]]; then
            # If "available templates" section exists, we insert after it
            sed -i "/available templates/ a \\
            \n$content\n" README.md
          else
            # If not, add the section at the end of the README
            echo -e "\n## Available Templates\n$content" >> README.md
          fi

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README table
          commit_user_name: GitHub Actions
          commit_user_email: github-actions[bot]@users.noreply.github.com
          branch: main  # Replace with your desired branch
          file_pattern: README.md
